nelmio_api_doc:
    documentation:
        info:
            title: watchShop
            description: API documentation
            version: 1.0.0
    areas:
        path_patterns:
            - ^/(?!/doc$) # Accepts routes under /api except /api/doc